name = "Epsilon 6 - Auxiliary"
prefix = "ep6_aux"
author = "Apostle Golden"
mainprefix = "z"

[files]
include = [
    "mod.cpp"
]

[version]
git_hash = 0

[lint.sqf]
enabled = true # Default: true

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf"
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]
